CFLAGS=		-ansi

all:		Caverage Ccp Ccat Cwc Csort

Caverage:	Caverage.c
					gcc $(CFLAGS) Caverage.c -o Caverage

Ccp:		Ccp.c
					gcc $(CFLAGS) Ccp.c -o Ccp

Ccat:		Ccat.c
					gcc $(CFLAGS) Ccat.c -o Ccat

Cwc:		Cwc.c
					gcc $(CFLAGS) Cwc.c -o Cwc

Csort:		Csort.c
					gcc $(CFLAGS) Csort.c -o Csort